import { Movie } from './types';

export const BANNED_WORDS = ['kill', 'murder', 'attack', 'hate', 'stupid', 'idiot', 'xxx', 'porn', 'nude', 'violence', 'blood', 'harm'];

export const INITIAL_MOVIES: Movie[] = [
  {
    id: 'm-dune2',
    title: "Dune: Part Two",
    type: "Movie",
    genre: ["Sci-Fi", "Action"],
    language: "English",
    availableLanguages: ["English", "Hindi", "Tamil", "Spanish"],
    year: 2024,
    rating: 4.9,
    ageRating: "PG-13",
    poster: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    about: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
    trailerId: "Way9Dexny3w",
    director: "Denis Villeneuve",
    cast: [{name: "Timothée Chalamet", image: "https://image.tmdb.org/t/p/w200/BE2sdjpgEHrT5l8lIiurIS5Jxo.jpg"}],
    availability: { platform: "IMAX", type: "Theater" },
    releaseDate: "2024-03-01",
    ottDate: "2024-05-21",
    boxOffice: { budget: "$190M", collection: "$711.8M", verdict: "Blockbuster" },
    status: "Released"
  },
  {
    id: 'm-mufasa',
    title: "Mufasa: The Lion King",
    type: "Movie",
    genre: ["Animation", "Drama"],
    language: "English",
    availableLanguages: ["English", "Hindi", "Telugu"],
    year: 2024,
    rating: 0,
    ageRating: "U",
    poster: "https://image.tmdb.org/t/p/w500/jbOSUAWMMI9x25sY0W3b4n69V0W.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/2P01Zl0tC7K6ZfG9l5z5fG9l5z5.jpg",
    about: "Simba, having become king of the Pride Lands, is determined for his cub to follow in his paw prints.",
    trailerId: "o17MF9vnabg",
    director: "Barry Jenkins",
    cast: [],
    availability: { platform: "Disney+", type: "OTT" },
    status: "Upcoming"
  },
  {
    id: 's-squid',
    title: "Squid Game",
    type: "Web Series",
    genre: ["Thriller", "Drama"],
    language: "Korean",
    availableLanguages: ["Korean", "English", "Hindi"],
    year: 2021,
    rating: 4.8,
    ageRating: "18+",
    poster: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/6wcC2t95vGEMkds2JUjJPuvx5f8.jpg",
    about: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games.",
    trailerId: "oqxAJKy0ii4",
    director: "Hwang Dong-hyuk",
    cast: [],
    availability: { platform: "Netflix", type: "OTT" },
    releaseDate: "2021-09-17",
    ottDate: "2021-09-17",
    boxOffice: { budget: "$21.4M", collection: "$900M (Value)", verdict: "Industry Hit" }
  },
  {
    id: 'm-kalki',
    title: "Kalki 2898 AD",
    type: "Movie",
    genre: ["Sci-Fi", "Action"],
    language: "Telugu",
    availableLanguages: ["Telugu", "Hindi", "Tamil", "Malayalam", "Kannada"],
    year: 2024,
    rating: 4.7,
    ageRating: "U/A 13+",
    poster: "https://image.tmdb.org/t/p/w500/lQf7Qe3e3F8eXg5g5g5g5g5g5g5.jpg", 
    backdrop: "https://image.tmdb.org/t/p/original/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
    about: "A modern avatar of Vishnu descends to Earth to protect the world from evil forces.",
    trailerId: "k24_k24", 
    director: "Nag Ashwin",
    cast: [{name: "Prabhas", image: ""}, {name: "Amitabh Bachchan", image: ""}],
    availability: { platform: "Theaters", type: "Theater" },
    releaseDate: "2024-06-27",
    ottDate: "2024-08-22",
    boxOffice: { budget: "₹600 Cr", collection: "₹1100 Cr+", verdict: "Super Hit" }
  },
  {
    id: 'm-stree2',
    title: "Stree 2",
    type: "Movie",
    genre: ["Horror", "Comedy"],
    language: "Hindi",
    availableLanguages: ["Hindi"],
    year: 2024,
    rating: 4.5,
    ageRating: "U/A 16+",
    poster: "https://image.tmdb.org/t/p/w500/cMD9Ygz11yjUhFs0OIldaCeNljN.jpg", 
    backdrop: "https://image.tmdb.org/t/p/original/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg",
    about: "The town of Chanderi is haunted again.",
    trailerId: "MCb13lbK500",
    director: "Amar Kaushik",
    cast: [],
    availability: { platform: "Theaters", type: "Theater" },
    releaseDate: "2024-08-15",
    ottDate: "2024-10-10",
    boxOffice: { budget: "₹60 Cr", collection: "₹800 Cr+", verdict: "All Time Blockbuster" }
  }
];